# Generated by Django 4.2.1 on 2023-06-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_create_date_comment_created_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="Create_date",
        ),
    ]
